import { defineStore } from "pinia";

export const useArmorStore = defineStore("armor", {
  state: () => ({
    fresirineArmor: {
      name: "Fresirine Armor",
      availableFromFloor: 10,
      price: 1000,
      oresToCraft: 100,
      imagePath: "/assets/armors/armor1.png",
      dmgMultiplier: 2,
    },
    ceymaniteArmor: {
      name: "Ceymanite Armor",
      availableFromFloor: 20,
      price: 2000,
      oresToCraft: 200,
      imagePath: "/assets/armors/armor2.png",
      dmgMultiplier: 4,
    },
    chintoidArmor: {
      name: "Chintoid Armor",
      availableFromFloor: 30,
      price: 3000,
      oresToCraft: 300,
      imagePath: "/assets/armors/armor3.png",
      dmgMultiplier: 6,
    },
    jasentineArmor: {
      name: "Jasentine Armor",
      availableFromFloor: 40,
      price: 4000,
      oresToCraft: 400,
      imagePath: "/assets/armors/armor4.png",
      dmgMultiplier: 8,
    },
    inyocociteArmor: {
      name: "Inyococite Armor",
      availableFromFloor: 50,
      price: 5000,
      oresToCraft: 500,
      imagePath: "/assets/armors/armor5.png",
      dmgMultiplier: 10,
    },
    pecoycraseArmor: {
      name: "Pecoycrase Armor",
      availableFromFloor: 60,
      price: 6000,
      oresToCraft: 600,
      imagePath: "/assets/armors/armor6.png",
      dmgMultiplier: 12,
    },
    demdingeriteArmor: {
      name: "Demdingerite Armor",
      availableFromFloor: 70,
      price: 7000,
      oresToCraft: 700,
      imagePath: "/assets/armors/armor7.png",
      dmgMultiplier: 14,
    },
    zirhemiteArmor: {
      name: "Zirhemite Armor",
      availableFromFloor: 80,
      price: 8000,
      oresToCraft: 800,
      imagePath: "/assets/armors/armor8.png",
      dmgMultiplier: 16,
    },
    conclaiteArmor: {
      name: "Conclaite Armor",
      availableFromFloor: 90,
      price: 9000,
      oresToCraft: 900,
      imagePath: "/assets/armors/armor9.png",
      dmgMultiplier: 18,
    },
    armors: [
      this.fresirineArmor,
      this.ceymaniteArmor,
      this.chintoidArmor,
      this.jasentineArmor,
      this.inyocociteArmor,
      this.pecoycraseArmor,
      this.demdingeriteArmor,
      this.zirhemiteArmor,
      this.conclaiteArmor,
    ],
  }),
  actions: {},
});
