import { defineStore } from "pinia";

export const usePlayerStore = defineStore("player", {
  state: () => ({
    playerDamage: 10,
    playerDefense: 10,
    playerLevel: 1,
    money: 0,
    floor: 1,
    monsterCount: 0,
    currentXP: 0,
    nextLevelXP: 50,
    avatar: {},
    playerInventory: [
      {
        equipmentName: "Regular Legplates",
        equipmentLevel: 1,
        equipmentDamage: 240,
        equipmentDefense: 165,
        equipmentRarity: 2,
        equipmentSlot: 5,
        price: 10,
        id: 1,
        picturePath: "src/assets/loot/legguards/legguards1.jpeg",
        dmgPercent: 0,
        defPercent: 0,
      },
      {
        equipmentName: "Regular Gauntlets",
        equipmentLevel: 1,
        equipmentDamage: 225,
        equipmentDefense: 165,
        equipmentRarity: 2,
        equipmentSlot: 4,
        price: 10,
        id: 2,
        picturePath: "src/assets/loot/gauntlets/gauntlets7.jpeg",
        dmgPercent: 0,
        defPercent: 0,
      },
      {
        equipmentName: "Fine Sabatons",
        equipmentLevel: 1,
        equipmentDamage: 240,
        equipmentDefense: 345,
        equipmentRarity: 3,
        equipmentSlot: 6,
        price: 15,
        id: 3,
        picturePath: "src/assets/loot/shoes/shoes3.jpeg",
        dmgPercent: 0,
        defPercent: 0,
      },
      {
        equipmentName: "Regular Legplates",
        equipmentLevel: 1,
        equipmentDamage: 255,
        equipmentDefense: 285,
        equipmentRarity: 2,
        equipmentSlot: 5,
        price: 10,
        id: 4,
        picturePath: "src/assets/loot/legguards/legguards1.jpeg",
        dmgPercent: 0,
        defPercent: 0,
      },
      {
        equipmentName: "Rusty Gauntlets",
        equipmentLevel: 1,
        equipmentDamage: 195,
        equipmentDefense: 225,
        equipmentRarity: 1,
        equipmentSlot: 4,
        price: 5,
        id: 5,
        picturePath: "src/assets/loot/gauntlets/gauntlets3.jpeg",
        dmgPercent: 0,
        defPercent: 0,
      },
      {
        equipmentName: "Fine Gauntlets",
        equipmentLevel: 1,
        equipmentDamage: 315,
        equipmentDefense: 270,
        equipmentRarity: 3,
        equipmentSlot: 4,
        price: 15,
        id: 6,
        picturePath: "src/assets/loot/gauntlets/gauntlets1.jpeg",
        dmgPercent: 0,
        defPercent: 0,
      },
      {
        equipmentName: "Regular Helmet",
        equipmentLevel: 1,
        equipmentDamage: 240,
        equipmentDefense: 285,
        equipmentRarity: 2,
        equipmentSlot: 1,
        price: 10,
        id: 7,
        picturePath: "src/assets/loot/helmet/helmet1.jpeg",
        dmgPercent: 0,
        defPercent: 0,
      },
      {
        equipmentName: "Rusty Ring",
        equipmentLevel: 1,
        equipmentDamage: 210,
        equipmentDefense: 180,
        equipmentRarity: 1,
        equipmentSlot: 7,
        price: 5,
        id: 8,
        picturePath: "src/assets/loot/ring/ring4.jpeg",
        dmgPercent: 0,
        defPercent: 0,
      },
      {
        equipmentName: "Regular Gauntlets",
        equipmentLevel: 1,
        equipmentDamage: 285,
        equipmentDefense: 165,
        equipmentRarity: 2,
        equipmentSlot: 4,
        price: 10,
        id: 9,
        picturePath: "src/assets/loot/gauntlets/gauntlets9.jpeg",
        dmgPercent: 0,
        defPercent: 0,
      },
      {
        equipmentName: "Rusty Legplates",
        equipmentLevel: 1,
        equipmentDamage: 150,
        equipmentDefense: 210,
        equipmentRarity: 1,
        equipmentSlot: 5,
        price: 5,
        id: 10,
        picturePath: "src/assets/loot/legguards/legguards1.jpeg",
        dmgPercent: 0,
        defPercent: 0,
      },
    ],
    itemStartId: 0,
    hasSavedGame: false,
  }),
  actions: {},
});
